
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: sample-crossplane-vpc
spec:
  forProvider:
    region: eu-west-2
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
    tags: 
     - key: Name
       value: sample-crossplane-vpc
     - key: ManagedBy 
       value: crossplane
  providerConfigRef:
    name: default
